// Generated by CoffeeScript 1.4.0
var Product,
  __hasProp = {}.hasOwnProperty;

Product = (function() {

  function Product(calories, protein, carbs, fat) {
    this.calories = calories != null ? parseFloat(calories) : 0;
    this.protein = protein != null ? parseFloat(protein) : 0;
    this.carbs = carbs != null ? parseFloat(carbs) : 0;
    this.fat = fat != null ? parseFloat(fat) : 0;
  }

  Product.prototype.add = function(macro) {
    var m, _results;
    _results = [];
    for (m in this) {
      if (!__hasProp.call(this, m)) continue;
      _results.push(this[m] += macro[m]);
    }
    return _results;
  };

  Product.prototype.multiply = function(multiplier) {
    var copy, m;
    copy = new Product(this.calories, this.protein, this.carbs, this.fat);
    for (m in this) {
      if (!__hasProp.call(this, m)) continue;
      copy[m] *= multiplier;
    }
    return copy;
  };

  return Product;

})();
